# -*- coding: utf-8 -*-
"""enterprise_rag_system.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7_DNRcZocAlJ7adc8gKnuQtmgxQY5mZ

## Setup for Enterprise RAG System

The tests in this notebook depend on the `enterprise_rag_system` module. This module is not a standard Python library and needs to be defined. Below is a placeholder for `enterprise_rag_system.py` that includes the classes and enumerations imported by your test suite. You will need to implement the actual logic within these classes for the tests to function correctly.
"""

import unittest
import time
import json
from datetime import datetime, timedelta
from typing import List, Dict, Tuple, Any
import uuid
from enum import Enum

# Placeholder for the enterprise_rag_system module

class UserRole(Enum):
    EXECUTIVE = "EXECUTIVE"
    MANAGER = "MANAGER"
    ANALYST = "ANALYST"
    CONTRACTOR = "CONTRACTOR"

class DataClassification(Enum):
    CONFIDENTIAL = "CONFIDENTIAL"
    RESTRICTED = "RESTRICTED"
    INTERNAL = "INTERNAL"
    PUBLIC = "PUBLIC"

class EnterpriseUser:
    def __init__(self, user_id: str, name: str, department: str, role: UserRole):
        self.user_id = user_id
        self.name = name
        self.department = department
        self.role = role
        self.session_id = str(uuid.uuid4()) # For test_session_isolation

class AccessPolicy:
    def __init__(
        self, data_id: str, classification: DataClassification,
        allowed_roles: List[UserRole], allowed_departments: List[str],
        expiration: datetime = None
    ):
        self.data_id = data_id
        self.classification = classification
        self.allowed_roles = allowed_roles
        self.allowed_departments = allowed_departments
        self.expiration = expiration

class RBACManager:
    def __init__(self):
        self.policies: Dict[str, AccessPolicy] = {}
        self.audit_log: List[Dict[str, Any]] = []

    def register_policy(self, policy: AccessPolicy):
        self.policies[policy.data_id] = policy

    def authorize_access(self, user: EnterpriseUser, data_id: str) -> Tuple[bool, str]:
        policy = self.policies.get(data_id)
        authorized = False
        reason = "Denied"

        if policy:
            if policy.expiration and datetime.now() > policy.expiration:
                reason = "Policy expired"
            elif user.role in policy.allowed_roles and user.department in policy.allowed_departments:
                authorized = True
                reason = "Access granted"
            else:
                reason = "Role or department not authorized"
        else:
            reason = "No policy found for data_id"

        self.audit_log.append({
            'timestamp': datetime.now(),
            'user_id': user.user_id,
            'data_id': data_id,
            'authorized': authorized,
            'reason': reason
        })
        return authorized, reason

    def get_audit_log(self) -> List[Dict[str, Any]]:
        return self.audit_log

class Document:
    def __init__(self, doc_id: str, source_type: str, content: str, metadata: Dict[str, Any]):
        self.doc_id = doc_id
        self.source_type = source_type
        self.content = content
        self.metadata = metadata

class DataSourceConnector:
    def __init__(self):
        pass

    def from_csv(self, file_path: str) -> List[Document]:
        # Placeholder implementation
        import csv
        docs = []
        with open(file_path, 'r') as f:
            reader = csv.DictReader(f)
            for i, row in enumerate(reader):
                docs.append(Document(str(i), 'csv', json.dumps(row), {'filepath': file_path}))
        return docs

    def from_json(self, file_path: str) -> List[Document]:
        # Placeholder implementation
        import json
        docs = []
        with open(file_path, 'r') as f:
            data = json.load(f)
            for i, item in enumerate(data):
                docs.append(Document(str(i), 'json', json.dumps(item), {'filepath': file_path}))
        return docs

    def from_text(self, file_path: str) -> List[Document]:
        # Placeholder implementation
        with open(file_path, 'r') as f:
            content = f.read()
        return [Document(str(uuid.uuid4()), 'text', content, {'filepath': file_path})]

class SemanticVectorStore:
    def __init__(self):
        self.documents: List[Document] = []

    def add_documents(self, documents: List[Document]):
        self.documents.extend(documents)

    def semantic_search(self, query: str, top_k: int = 5, threshold: float = 0.0) -> List[Tuple[Document, str, float]]:
        # Placeholder implementation - returns dummy results for testing structure
        results = []
        for doc in self.documents:
            # Simple content check for demonstration, replace with actual semantic similarity
            if query.lower() in doc.content.lower():
                results.append((doc, doc.content, 0.8)) # Dummy score
            if len(results) >= top_k: break
        return results

    def hybrid_search(self, query: str, top_k: int = 5) -> List[Tuple[Document, str, float]]:
        # Placeholder implementation - combines semantic and keyword
        semantic_res = self.semantic_search(query, top_k)
        keyword_res = [(doc, doc.content, 0.5) for doc in self.documents if query.split(' ')[0].lower() in doc.content.lower()][:top_k]
        return list(set(semantic_res + keyword_res))

class Answer:
    def __init__(self, answer_text: str, citations: List[Dict[str, Any]], confidence_score: float):
        self.answer_text = answer_text
        self.citations = citations
        self.confidence_score = confidence_score

class AnswerGenerator:
    def __init__(self):
        pass

    def generate_answer(self, query: str, chunks: List[Tuple[Document, str, float, str]], user: EnterpriseUser) -> Answer:
        # Placeholder implementation
        citation_list = []
        combined_content = []
        total_score = 0

        for doc, content_chunk, score, _type in chunks:
            citation_list.append({
                'doc_id': doc.doc_id,
                'source': doc.metadata.get('source', 'unknown'),
                'page': doc.metadata.get('page', 'N/A'),
                'content_chunk': content_chunk
            })
            combined_content.append(content_chunk)
            total_score += score

        avg_confidence = total_score / len(chunks) if chunks else 0.0

        # Simple answer generation for testing structure
        answer_text = f"Based on the provided information, the query '{query}' relates to: {' '.join(combined_content)}. User {user.name} was querying."

        return Answer(answer_text, citation_list, avg_confidence)

class EnterpriseRAGSystem:
    def __init__(self):
        self.rbac_manager = RBACManager()
        self.data_connector = DataSourceConnector()
        self.vector_store = SemanticVectorStore()
        self.answer_generator = AnswerGenerator()

    def ingest_data(self, file_path: str, data_type: str, classification: DataClassification, allowed_roles: List[UserRole], allowed_departments: List[str]) -> str:
        # Placeholder implementation
        docs = []
        if data_type == 'text':
            docs = self.data_connector.from_text(file_path)
        elif data_type == 'csv':
            docs = self.data_connector.from_csv(file_path)
        elif data_type == 'json':
            docs = self.data_connector.from_json(file_path)

        if docs:
            for doc in docs:
                self.vector_store.add_documents([doc])
                policy = AccessPolicy(
                    data_id=doc.doc_id,
                    classification=classification,
                    allowed_roles=allowed_roles,
                    allowed_departments=allowed_departments
                )
                self.rbac_manager.register_policy(policy)
            return docs[0].doc_id # Return the ID of the first document for testing
        return None

    def query(self, query: str, user: EnterpriseUser) -> Tuple[Answer, str]:
        # Placeholder implementation
        # Perform search
        search_results = self.vector_store.semantic_search(query, top_k=5)

        # Filter based on RBAC
        authorized_chunks = []
        security_status = "RBAC Check: "
        for doc, chunk_content, score in search_results:
            authorized, reason = self.rbac_manager.authorize_access(user, doc.doc_id)
            security_status += f"({doc.doc_id}: {reason}) "
            if authorized:
                authorized_chunks.append((doc, chunk_content, score, "semantic"))

        if not authorized_chunks:
            return Answer("Access denied or no relevant information found.", [], 0.0), security_status

        # Generate answer
        answer = self.answer_generator.generate_answer(query, authorized_chunks, user)
        return answer, security_status

"""### Fixing Module Not Found Error

To allow the test suite to import `enterprise_rag_system`, we need to save the module's definition into a Python file (`enterprise_rag_system.py`). The following cell will create this file in your current directory. Please run it.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile enterprise_rag_system.py
# import unittest
# import time
# import json
# from datetime import datetime, timedelta
# from typing import List, Dict, Tuple, Any
# import uuid
# from enum import Enum
# 
# # Placeholder for the enterprise_rag_system module
# 
# class UserRole(Enum):
#     EXECUTIVE = "EXECUTIVE"
#     MANAGER = "MANAGER"
#     ANALYST = "ANALYST"
#     CONTRACTOR = "CONTRACTOR"
# 
# class DataClassification(Enum):
#     CONFIDENTIAL = "CONFIDENTIAL"
#     RESTRICTED = "RESTRICTED"
#     INTERNAL = "INTERNAL"
#     PUBLIC = "PUBLIC"
# 
# class EnterpriseUser:
#     def __init__(self, user_id: str, name: str, department: str, role: UserRole):
#         self.user_id = user_id
#         self.name = name
#         self.department = department
#         self.role = role
#         self.session_id = str(uuid.uuid4()) # For test_session_isolation
# 
# class AccessPolicy:
#     def __init__(
#         self, data_id: str, classification: DataClassification,
#         allowed_roles: List[UserRole], allowed_departments: List[str],
#         expiration: datetime = None
#     ):
#         self.data_id = data_id
#         self.classification = classification
#         self.allowed_roles = allowed_roles
#         self.allowed_departments = allowed_departments
#         self.expiration = expiration
# 
# class RBACManager:
#     def __init__(self):
#         self.policies: Dict[str, AccessPolicy] = {}
#         self.audit_log: List[Dict[str, Any]] = []
# 
#     def register_policy(self, policy: AccessPolicy):
#         self.policies[policy.data_id] = policy
# 
#     def authorize_access(self, user: EnterpriseUser, data_id: str) -> Tuple[bool, str]:
#         policy = self.policies.get(data_id)
#         authorized = False
#         reason = "Denied"
# 
#         if policy:
#             if policy.expiration and datetime.now() > policy.expiration:
#                 reason = "Policy expired"
#             elif user.role in policy.allowed_roles and user.department in policy.allowed_departments:
#                 authorized = True
#                 reason = "Access granted"
#             else:
#                 reason = "Role or department not authorized"
#         else:
#             reason = "No policy found for data_id"
# 
#         self.audit_log.append({
#             'timestamp': datetime.now(),
#             'user_id': user.user_id,
#             'data_id': data_id,
#             'authorized': authorized,
#             'reason': reason
#         })
#         return authorized, reason
# 
#     def get_audit_log(self) -> List[Dict[str, Any]]: # Corrected signature: added self
#         return self.audit_log
# 
# class Document:
#     def __init__(self, doc_id: str, source_type: str, content: str, metadata: Dict[str, Any]):
#         self.doc_id = doc_id
#         self.source_type = source_type
#         self.content = content
#         self.metadata = metadata
# 
# class DataSourceConnector:
#     def __init__(self):
#         pass
# 
#     def from_csv(self, file_path: str) -> List[Document]:
#         # Placeholder implementation
#         import csv
#         docs = []
#         with open(file_path, 'r') as f:
#             reader = csv.DictReader(f)
#             for i, row in enumerate(reader):
#                 docs.append(Document(str(i), 'csv', json.dumps(row), {'filepath': file_path}))
#         return docs
# 
#     def from_json(self, file_path: str) -> List[Document]:
#         # Placeholder implementation
#         import json
#         docs = []
#         with open(file_path, 'r') as f:
#             data = json.load(f)
#             for i, item in enumerate(data):
#                 docs.append(Document(str(i), 'json', json.dumps(item), {'filepath': file_path}))
#         return docs
# 
#     def from_text(self, file_path: str) -> List[Document]:
#         # Placeholder implementation
#         with open(file_path, 'r') as f:
#             content = f.read()
#         return [Document(str(uuid.uuid4()), 'text', content, {'filepath': file_path})]
# 
# class SemanticVectorStore:
#     def __init__(self):
#         self.documents: List[Document] = []
# 
#     def add_documents(self, documents: List[Document]):
#         self.documents.extend(documents)
# 
#     def semantic_search(self, query: str, top_k: int = 5, threshold: float = 0.0) -> List[Tuple[Document, str, float]]:
#         # Placeholder implementation - returns dummy results for testing structure
#         results = []
#         query_words = query.lower().split() # Split query into words
#         for doc in self.documents:
#             doc_content_lower = doc.content.lower()
#             # Check if any word from the query is in the document content
#             if any(word in doc_content_lower for word in query_words):
#                 results.append((doc, doc.content, 0.8)) # Dummy score
#             if len(results) >= top_k: break
#         return results
# 
#     def hybrid_search(self, query: str, top_k: int = 5) -> List[Tuple[Document, str, float]]:
#         # Placeholder implementation - combines semantic and keyword
#         semantic_res = self.semantic_search(query, top_k)
#         keyword_res = [(doc, doc.content, 0.5) for doc in self.documents if query.split(' ')[0].lower() in doc.content.lower()][:top_k]
#         return list(set(semantic_res + keyword_res))
# 
# class Answer:
#     def __init__(self, answer_text: str, citations: List[Dict[str, Any]], confidence_score: float):
#         self.answer_text = answer_text
#         self.citations = citations
#         self.confidence_score = confidence_score
# 
# class AnswerGenerator:
#     def __init__(self):
#         pass
# 
#     def generate_answer(self, query: str, chunks: List[Tuple[Document, str, float, str]], user: EnterpriseUser) -> Answer:
#         # Placeholder implementation
#         citation_list = []
#         combined_content = []
#         total_score = 0
# 
#         for doc, content_chunk, score, _type in chunks:
#             citation_list.append({
#                 'doc_id': doc.doc_id,
#                 'source': doc.metadata.get('source', 'unknown'),
#                 'page': doc.metadata.get('page', 'N/A'),
#                 'content_chunk': content_chunk
#             })
#             combined_content.append(content_chunk)
#             total_score += score
# 
#         avg_confidence = total_score / len(chunks) if chunks else 0.0
# 
#         # Simple answer generation for testing structure
#         answer_text = f"Based on the provided information, the query '{query}' relates to: {' '.join(combined_content)}. User {user.name} was querying."
# 
#         return Answer(answer_text, citation_list, avg_confidence)
# 
# class EnterpriseRAGSystem:
#     def __init__(self):
#         self.rbac_manager = RBACManager()
#         self.data_connector = DataSourceConnector()
#         self.vector_store = SemanticVectorStore()
#         self.answer_generator = AnswerGenerator()
# 
#     def ingest_data(self, file_path: str, data_type: str, classification: DataClassification, allowed_roles: List[UserRole], allowed_departments: List[str]) -> str:
#         # Placeholder implementation
#         docs = []
#         if data_type == 'text':
#             docs = self.data_connector.from_text(file_path)
#         elif data_type == 'csv':
#             docs = self.data_connector.from_csv(file_path)
#         elif data_type == 'json':
#             docs = self.data_connector.from_json(file_path)
# 
#         if docs:
#             for doc in docs:
#                 self.vector_store.add_documents([doc])
#                 policy = AccessPolicy(
#                     data_id=doc.doc_id,
#                     classification=classification,
#                     allowed_roles=allowed_roles,
#                     allowed_departments=allowed_departments
#                 )
#                 self.rbac_manager.register_policy(policy)
#             return docs[0].doc_id # Return the ID of the first document for testing
#         return None
# 
#     def query(self, query: str, user: EnterpriseUser) -> Tuple[Answer, str]:
#         # Placeholder implementation
#         # Perform search
#         search_results = self.vector_store.semantic_search(query, top_k=5)
# 
#         # Filter based on RBAC
#         authorized_chunks = []
#         security_status = "RBAC Check: "
#         for doc, chunk_content, score in search_results:
#             authorized, reason = self.rbac_manager.authorize_access(user, doc.doc_id)
#             security_status += f"({doc.doc_id}: {reason}) "
#             if authorized:
#                 authorized_chunks.append((doc, chunk_content, score, "semantic"))
# 
#         if not authorized_chunks:
#             return Answer("Access denied or no relevant information found.", [], 0.0), security_status
# 
#         # Generate answer
#         answer = self.answer_generator.generate_answer(query, authorized_chunks, user)
#         return answer, security_status
#

"""After running the above cell to create `enterprise_rag_system.py`, please re-run the test suite cell (`i5xkvT4ibHtW`)."""

import unittest
import time
import json
from datetime import datetime, timedelta
from typing import List, Dict, Tuple
import importlib # Added importlib
import enterprise_rag_system # Import the module

# Reload the module to ensure latest changes are picked up
importlib.reload(enterprise_rag_system)

# ============================================================================
# 1. UNIT TESTS
# ============================================================================

class TestRBACManager(unittest.TestCase):
    """Test Role-Based Access Control functionality"""

    def setUp(self):
        from enterprise_rag_system import (
            RBACManager, AccessPolicy, EnterpriseUser,
            UserRole, DataClassification
        )
        self.rbac = RBACManager()
        self.user_exec = EnterpriseUser(
            user_id="exec_001",
            name="Sarah Chen",
            department="Finance",
            role=UserRole.EXECUTIVE
        )
        self.user_contractor = EnterpriseUser(
            user_id="contractor_001",
            name="Alex Rodriguez",
            department="Operations",
            role=UserRole.CONTRACTOR
        )

    def test_authorized_access_executive(self):
        """Test that executive can access confidential data"""
        from enterprise_rag_system import AccessPolicy, UserRole, DataClassification

        policy = AccessPolicy(
            data_id="doc_123",
            classification=DataClassification.CONFIDENTIAL,
            allowed_roles=[UserRole.EXECUTIVE, UserRole.MANAGER],
            allowed_departments=["Finance", "Operations"]
        )
        self.rbac.register_policy(policy)

        authorized, reason = self.rbac.authorize_access(self.user_exec, "doc_123")
        self.assertTrue(authorized)
        self.assertEqual(reason, "Access granted")

    def test_denied_access_contractor(self):
        """Test that contractor cannot access executive data"""
        from enterprise_rag_system import AccessPolicy, UserRole, DataClassification

        policy = AccessPolicy(
            data_id="doc_exec",
            classification=DataClassification.RESTRICTED,
            allowed_roles=[UserRole.EXECUTIVE],
            allowed_departments=["Finance"]
        )
        self.rbac.register_policy(policy)

        authorized, reason = self.rbac.authorize_access(self.user_contractor, "doc_exec")
        self.assertFalse(authorized)

    def test_audit_logging(self):
        """Test that all access attempts are logged"""
        from enterprise_rag_system import AccessPolicy, UserRole, DataClassification

        policy = AccessPolicy(
            data_id="doc_audit",
            classification=DataClassification.INTERNAL,
            allowed_roles=[UserRole.ANALYST],
            allowed_departments=["Engineering"]
        )
        self.rbac.register_policy(policy)

        # Multiple access attempts
        for _ in range(3):
            self.rbac.authorize_access(self.user_exec, "doc_audit")

        logs = self.rbac.get_audit_log()
        self.assertEqual(len(logs), 3)
        self.assertTrue(all(log['data_id'] == 'doc_audit' for log in logs))

    def test_policy_expiration(self):
        """Test that expired policies deny access"""
        from enterprise_rag_system import AccessPolicy, UserRole, DataClassification

        # Create expired policy
        policy = AccessPolicy(
            data_id="doc_expired",
            classification=DataClassification.INTERNAL,
            allowed_roles=[UserRole.ANALYST],
            allowed_departments=["Engineering"],
            expiration=datetime.now() - timedelta(hours=1)  # Expired
        )
        self.rbac.register_policy(policy)

        authorized, _ = self.rbac.authorize_access(self.user_exec, "doc_expired")
        self.assertFalse(authorized)


class TestDataIngestion(unittest.TestCase):
    """Test multi-source data ingestion"""

    def setUp(self):
        from enterprise_rag_system import DataSourceConnector
        self.connector = DataSourceConnector()

    def test_csv_ingestion(self):
        """Test CSV data ingestion"""
        import csv
        import tempfile

        # Create test CSV
        with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False) as f:
            writer = csv.DictWriter(f, fieldnames=['id', 'name', 'value'])
            writer.writeheader()
            writer.writerow({'id': '1', 'name': 'test', 'value': '100'})
            csv_path = f.name

        docs = self.connector.from_csv(csv_path)
        self.assertEqual(len(docs), 1)
        self.assertIn('id', docs[0].content) # Fixed: docs[0].content

    def test_json_ingestion(self):
        """Test JSON data ingestion"""
        import json
        import tempfile

        # Create test JSON
        test_data = [
            {'id': 1, 'name': 'Alice', 'role': 'engineer'},
            {'id': 2, 'name': 'Bob', 'role': 'manager'}
        ]
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
            json.dump(test_data, f)
            json_path = f.name

        docs = self.connector.from_json(json_path)
        self.assertEqual(len(docs), 2)
        self.assertIn('Alice', docs[0].content) # Fixed: docs[0].content

    def test_text_ingestion(self):
        """Test plain text file ingestion"""
        import tempfile

        # Create test text file
        with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
            f.write("This is a test document.\nIt has multiple lines.")
            text_path = f.name

        docs = self.connector.from_text(text_path)
        self.assertEqual(len(docs), 1)
        self.assertIn('test document', docs[0].content) # Fixed: docs[0].content


class TestVectorStore(unittest.TestCase):
    """Test semantic search functionality"""

    def setUp(self):
        from enterprise_rag_system import SemanticVectorStore, Document, DataClassification

        self.store = SemanticVectorStore()

        # Create test documents
        self.docs = [
            Document(
                doc_id="doc_1",
                source_type="text",
                content="The Q3 2026 revenue was $2.4 million with strong growth",
                metadata={'source': 'financial_report.txt'}
            ),
            Document(
                doc_id="doc_2",
                source_type="text",
                content="Operating expenses increased due to expanded team",
                metadata={'source': 'report.txt'}
            ),
            Document(
                doc_id="doc_3",
                source_type="text",
                content="Customer satisfaction scores improved to 95%",
                metadata={'source': 'survey.txt'}
            )
        ]

        self.store.add_documents(self.docs)

    def test_semantic_search(self):
        """Test semantic search returns relevant results"""
        results = self.store.semantic_search("Q3 revenue", top_k=1)

        self.assertGreater(len(results), 0)
        self.assertIn("Q3", results[0][1])  # Check if result contains Q3

    def test_hybrid_search(self):
        """Test hybrid search combines semantic and keyword results"""
        results = self.store.hybrid_search("revenue growth", top_k=3)

        self.assertGreater(len(results), 0)
        self.assertLessEqual(len(results), 3)

    def test_search_threshold(self):
        """Test that results respect similarity threshold"""
        results = self.store.semantic_search(
            "completely unrelated topic xyz abc",
            top_k=5,
            threshold=0.5
        )

        # Low threshold should still return some results
        # High threshold might return none
        for _, _, score in results:
            self.assertGreaterEqual(score, 0.0)


class TestAnswerGeneration(unittest.TestCase):
    """Test answer generation with citations"""

    def setUp(self):
        from enterprise_rag_system import AnswerGenerator, Document, EnterpriseUser, UserRole

        self.generator = AnswerGenerator()
        self.user = EnterpriseUser(
            user_id="test_001",
            name="Test User",
            department="Test",
            role=UserRole.ANALYST
        )

        self.doc = Document(
            doc_id="doc_test",
            source_type="text",
            content="Q3 2026 revenue was $2.4M with 15% YoY growth",
            metadata={'source': 'financial.txt', 'page': 5}
        )

    def test_answer_with_citations(self):
        """Test that answers include proper citations"""
        from enterprise_rag_system import Document

        query = "What was Q3 revenue?"
        chunks = [(self.doc, "Q3 revenue was $2.4M", 0.95, "semantic")]

        answer = self.generator.generate_answer(query, chunks, self.user)

        self.assertGreater(len(answer.answer_text), 0)
        self.assertGreater(len(answer.citations), 0)
        self.assertGreater(answer.confidence_score, 0)

    def test_confidence_scoring(self):
        """Test that confidence scores are properly calculated"""
        query = "Q3 financial results?"
        chunks = [
            (self.doc, "High confidence text", 0.95, "semantic"),
            (self.doc, "Lower confidence text", 0.60, "keyword")
        ]

        answer = self.generator.generate_answer(query, chunks, self.user)

        self.assertGreater(answer.confidence_score, 0)
        self.assertLessEqual(answer.confidence_score, 1.0)


# ============================================================================
# 2. INTEGRATION TESTS
# ============================================================================

class TestEnterpriseRAGPipeline(unittest.TestCase):
    """Test complete RAG pipeline"""

    def setUp(self):
        from enterprise_rag_system import (
            EnterpriseRAGSystem, EnterpriseUser,
            UserRole, DataClassification
        )
        import tempfile

        self.rag = EnterpriseRAGSystem()
        self.user = EnterpriseUser(
            user_id="pipeline_test",
            name="Pipeline Test",
            department="Engineering",
            role=UserRole.ANALYST
        )

        # Create test document
        self.temp_file = tempfile.NamedTemporaryFile(
            mode='w',
            suffix='.txt',
            delete=False
        )
        self.temp_file.write("Test document with revenue information")
        self.temp_file.close()

    def test_full_pipeline(self):
        """Test complete ingest -> query -> answer flow"""
        from enterprise_rag_system import DataClassification, UserRole

        # Ingest
        doc_id = self.rag.ingest_data(
            file_path=self.temp_file.name,
            data_type='text',
            classification=DataClassification.INTERNAL,
            allowed_roles=[UserRole.ANALYST],
            allowed_departments=["Engineering"]
        )

        self.assertIsNotNone(doc_id)

        # Query
        answer, security_status = self.rag.query(
            query="What information is in the document?",
            user=self.user
        )

        self.assertIsNotNone(answer)
        self.assertGreater(len(answer.answer_text), 0)
        self.assertIn("RBAC", security_status)


# ============================================================================
# 3. PERFORMANCE TESTS
# ============================================================================

class PerformanceBenchmark:
    """Benchmark system performance"""

    @staticmethod
    def measure_query_latency(rag_system, queries: List[str], iterations: int = 10) -> Dict:
        """Measure query execution latency"""
        from enterprise_rag_system import EnterpriseUser, UserRole

        user = EnterpriseUser(
            user_id="bench_user",
            name="Benchmark",
            department="Eng",
            role=UserRole.ANALYST
        )

        latencies = []

        for query in queries:
            times = []
            for _ in range(iterations):
                start = time.time()
                rag_system.query(query, user)
                times.append((time.time() - start) * 1000)  # Convert to ms

            latencies.append({
                'query': query[:50],
                'p50': sorted(times)[len(times)//2],
                'p95': sorted(times)[int(len(times)*0.95)],
                'p99': sorted(times)[int(len(times)*0.99)],
                'avg': sum(times) / len(times)
            })

        return latencies

    @staticmethod
    def measure_throughput(rag_system, concurrent_users: int = 100) -> Dict:
        """Measure system throughput (queries per second)"""
        import threading

        query = "Test query for throughput measurement"
        results = {'success': 0, 'failure': 0, 'total_time': 0}
        lock = threading.Lock()

        def worker():
            from enterprise_rag_system import EnterpriseUser, UserRole

            user = EnterpriseUser(
                user_id=f"thread_user",
                name="Thread",
                department="Eng",
                role=UserRole.ANALYST
            )

            start = time.time()
            try:
                rag_system.query(query, user)
                with lock:
                    results['success'] += 1
            except:
                with lock:
                    results['failure'] += 1
            finally:
                with lock:
                    results['total_time'] += time.time() - start

        threads = [threading.Thread(target=worker) for _ in range(concurrent_users)]
        start_time = time.time()

        for t in threads:
            t.start()
        for t in threads:
            t.join()

        elapsed = time.time() - start_time
        qps = concurrent_users / elapsed

        return {
            'concurrent_users': concurrent_users,
            'successful_queries': results['success'],
            'failed_queries': results['failure'],
            'qps': qps,
            'avg_response_time_ms': (results['total_time'] / concurrent_users) * 1000
        }

    @staticmethod
    def measure_memory_usage(rag_system) -> Dict:
        """Measure memory consumption"""
        import sys

        def get_size(obj, seen=None):
            """Recursively find size of objects"""
            size = sys.getsizeof(obj)
            if seen is None:
                seen = set()

            obj_id = id(obj)
            if obj_id in seen:
                return 0

            seen.add(obj_id)

            if isinstance(obj, dict):
                size += sum([get_size(v, seen) for v in obj.values()])
            elif hasattr(obj, '__dict__'):
                size += get_size(obj.__dict__, seen)
            elif hasattr(obj, '__iter__') and not isinstance(obj, (str, bytes, bytearray)):
                size += sum([get_size(i, seen) for i in obj])

            return size

        return {
            'rag_system_size_mb': get_size(rag_system) / (1024**2),
            'vector_store_size_mb': get_size(rag_system.vector_store) / (1024**2),
            'rbac_manager_size_mb': get_size(rag_system.rbac_manager) / (1024**2)
        }


# ============================================================================
# 4. SECURITY TESTS
# ============================================================================

class SecurityTests(unittest.TestCase):
    """Test security features"""

    def test_session_isolation(self):
        """Test that sessions are properly isolated"""
        from enterprise_rag_system import EnterpriseUser, UserRole

        user1 = EnterpriseUser(
            user_id="user1",
            name="User 1",
            department="Finance",
            role=UserRole.EXECUTIVE
        )

        user2 = EnterpriseUser(
            user_id="user2",
            name="User 2",
            department="Engineering",
            role=UserRole.ANALYST
        )

        # Sessions should be different
        self.assertNotEqual(user1.session_id, user2.session_id)

    def test_rbac_enforcement(self):
        """Test RBAC is enforced at query time"""
        from enterprise_rag_system import (
            EnterpriseRAGSystem, EnterpriseUser, UserRole,
            DataClassification
        )
        import tempfile

        rag = EnterpriseRAGSystem()

        # Create restricted document
        with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
            f.write("Restricted financial data")
            path = f.name

        # Ingest with executive-only access
        rag.ingest_data(
            file_path=path,
            data_type='text',
            classification=DataClassification.RESTRICTED,
            allowed_roles=[UserRole.EXECUTIVE],
            allowed_departments=["Finance"]
        )

        # Try to query as contractor
        contractor = EnterpriseUser(
            user_id="contractor",
            name="Contractor",
            department="Operations",
            role=UserRole.CONTRACTOR
        )

        answer, status = rag.query("What's the data?", contractor)

        # Contractor should get limited results
        self.assertIn("RBAC", status)

    def test_audit_trail_completeness(self):
        """Test that audit trail is complete"""
        from enterprise_rag_system import (
            RBACManager, AccessPolicy, EnterpriseUser,
            UserRole, DataClassification
        )

        rbac = RBACManager()
        user = EnterpriseUser(
            user_id="audit_test",
            name="Audit Test",
            department="Eng",
            role=UserRole.ANALYST
        )

        policy = AccessPolicy(
            data_id="doc_audit",
            classification=DataClassification.INTERNAL,
            allowed_roles=[UserRole.ANALYST],
            allowed_departments=["Engineering"]
        )
        rbac.register_policy(policy)

        # Make access attempt
        rbac.authorize_access(user, "doc_audit")

        # Check audit log
        logs = rbac.get_audit_log()
        self.assertGreater(len(logs), 0)

        latest = logs[-1]
        self.assertEqual(latest['user_id'], user.user_id)
        self.assertIn('timestamp', latest)
        self.assertIn('authorized', latest)


# ============================================================================
# 5. TEST RUNNER
# ============================================================================

def run_all_tests():
    """Run complete test suite"""

    print("="*80)
    print("ENTERPRISE RAG SYSTEM - COMPREHENSIVE TEST SUITE")
    print("="*80)

    # Create test suite
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()

    # Add all test classes
    suite.addTests(loader.loadTestsFromTestCase(TestRBACManager))
    suite.addTests(loader.loadTestsFromTestCase(TestDataIngestion))
    suite.addTests(loader.loadTestsFromTestCase(TestVectorStore))
    suite.addTests(loader.loadTestsFromTestCase(TestAnswerGeneration))
    suite.addTests(loader.loadTestsFromTestCase(TestEnterpriseRAGPipeline))
    suite.addTests(loader.loadTestsFromTestCase(SecurityTests))

    # Run tests
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)

    # Print summary
    print("\n" + "="*80)
    print("TEST SUMMARY")
    print("="*80)
    print(f"Tests run: {result.testsRun}")
    print(f"Successes: {result.testsRun - len(result.failures) - len(result.errors)}")
    print(f"Failures: {len(result.failures)}")
    print(f"Errors: {len(result.errors)}")
    print(f"Success Rate: {((result.testsRun - len(result.failures) - len(result.errors)) / result.testsRun * 100):.1f}%")

    return result.wasSuccessful()


if __name__ == '__main__':
    success = run_all_tests()
    exit(0 if success else 1)

"""## Example Usage of Enterprise RAG System

This example demonstrates the core workflow of the `EnterpriseRAGSystem`: data ingestion with RBAC policies, and querying the system with different user roles to observe access control in action.
"""

import tempfile
import os

# Import necessary classes from the module
from enterprise_rag_system import (
    EnterpriseRAGSystem, EnterpriseUser, UserRole,
    DataClassification, Answer
)

print("Initializing Enterprise RAG System...")
rag_system = EnterpriseRAGSystem()

# 1. Create a dummy document for ingestion
print("Creating a dummy document...")
executive_doc_content = "This document contains sensitive Q4 financial projections for 2024, accessible only to Executive and Finance department."

with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
    f.write(executive_doc_content)
    executive_doc_path = f.name

# 2. Ingest the document with specific RBAC policies
print(f"Ingesting document '{executive_doc_path}' with Executive-only access...")
doc_id = rag_system.ingest_data(
    file_path=executive_doc_path,
    data_type='text',
    classification=DataClassification.CONFIDENTIAL,
    allowed_roles=[UserRole.EXECUTIVE],
    allowed_departments=["Finance", "Operations", "Executive Board"]
)

print(f"Document ingested with ID: {doc_id}")

# 3. Create users with different roles
executive_user = EnterpriseUser(
    user_id="exec_jane",
    name="Jane Doe",
    department="Finance",
    role=UserRole.EXECUTIVE
)

contractor_user = EnterpriseUser(
    user_id="contr_john",
    name="John Smith",
    department="Operations",
    role=UserRole.CONTRACTOR
)

print("\n--- Querying as Executive User ---")
query = "What are the Q4 financial projections?"
executive_answer, exec_security_status = rag_system.query(query, executive_user)

print(f"Executive User ({executive_user.name}) Query: '{query}'")
print(f"Answer: {executive_answer.answer_text}")
print(f"Confidence: {executive_answer.confidence_score:.2f}")
print(f"Security Status: {exec_security_status}")
print("Citations:")
for citation in executive_answer.citations:
    print(f"  - Doc ID: {citation['doc_id']}, Source: {citation['source']}, Chunk: {citation['content_chunk'][:50]}...")

print("\n--- Querying as Contractor User ---")
contractor_answer, contr_security_status = rag_system.query(query, contractor_user)

print(f"Contractor User ({contractor_user.name}) Query: '{query}'")
print(f"Answer: {contractor_answer.answer_text}")
print(f"Confidence: {contractor_answer.confidence_score:.2f}")
print(f"Security Status: {contr_security_status}")

# Clean up the temporary file
os.remove(executive_doc_path)
print(f"\nCleaned up temporary file: {executive_doc_path}")

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install pypdf

"""The `pypdf` library has been installed. Now, I will update the `enterprise_rag_system.py` file to include PDF ingestion capabilities. This involves adding a new method `from_pdf` to `DataSourceConnector` and updating the `ingest_data` method in `EnterpriseRAGSystem` to use it.

After updating the module, I'll provide a new test case to demonstrate PDF ingestion.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile enterprise_rag_system.py
# import unittest
# import time
# import json
# from datetime import datetime, timedelta
# from typing import List, Dict, Tuple, Any
# import uuid
# from enum import Enum
# import pypdf # Added for PDF processing
# 
# # Placeholder for the enterprise_rag_system module
# 
# class UserRole(Enum):
#     EXECUTIVE = "EXECUTIVE"
#     MANAGER = "MANAGER"
#     ANALYST = "ANALYST"
#     CONTRACTOR = "CONTRACTOR"
# 
# class DataClassification(Enum):
#     CONFIDENTIAL = "CONFIDENTIAL"
#     RESTRICTED = "RESTRICTED"
#     INTERNAL = "INTERNAL"
#     PUBLIC = "PUBLIC"
# 
# class EnterpriseUser:
#     def __init__(self, user_id: str, name: str, department: str, role: UserRole):
#         self.user_id = user_id
#         self.name = name
#         self.department = department
#         self.role = role
#         self.session_id = str(uuid.uuid4()) # For test_session_isolation
# 
# class AccessPolicy:
#     def __init__(
#         self, data_id: str, classification: DataClassification,
#         allowed_roles: List[UserRole], allowed_departments: List[str],
#         expiration: datetime = None
#     ):
#         self.data_id = data_id
#         self.classification = classification
#         self.allowed_roles = allowed_roles
#         self.allowed_departments = allowed_departments
#         self.expiration = expiration
# 
# class RBACManager:
#     def __init__(self):
#         self.policies: Dict[str, AccessPolicy] = {}
#         self.audit_log: List[Dict[str, Any]] = []
# 
#     def register_policy(self, policy: AccessPolicy):
#         self.policies[policy.data_id] = policy
# 
#     def authorize_access(self, user: EnterpriseUser, data_id: str) -> Tuple[bool, str]:
#         policy = self.policies.get(data_id)
#         authorized = False
#         reason = "Denied"
# 
#         if policy:
#             if policy.expiration and datetime.now() > policy.expiration:
#                 reason = "Policy expired"
#             elif user.role in policy.allowed_roles and user.department in policy.allowed_departments:
#                 authorized = True
#                 reason = "Access granted"
#             else:
#                 reason = "Role or department not authorized"
#         else:
#             reason = "No policy found for data_id"
# 
#         self.audit_log.append({
#             'timestamp': datetime.now(),
#             'user_id': user.user_id,
#             'data_id': data_id,
#             'authorized': authorized,
#             'reason': reason
#         })
#         return authorized, reason
# 
#     def get_audit_log(self) -> List[Dict[str, Any]]: # Corrected signature: added self
#         return self.audit_log
# 
# class Document:
#     def __init__(self, doc_id: str, source_type: str, content: str, metadata: Dict[str, Any]):
#         self.doc_id = doc_id
#         self.source_type = source_type
#         self.content = content
#         self.metadata = metadata
# 
# class DataSourceConnector:
#     def __init__(self):
#         pass
# 
#     def from_csv(self, file_path: str) -> List[Document]:
#         # Placeholder implementation
#         import csv
#         docs = []
#         with open(file_path, 'r') as f:
#             reader = csv.DictReader(f)
#             for i, row in enumerate(reader):
#                 docs.append(Document(str(i), 'csv', json.dumps(row), {'filepath': file_path}))
#         return docs
# 
#     def from_json(self, file_path: str) -> List[Document]:
#         # Placeholder implementation
#         import json
#         docs = []
#         with open(file_path, 'r') as f:
#             data = json.load(f)
#             for i, item in enumerate(data):
#                 docs.append(Document(str(i), 'json', json.dumps(item), {'filepath': file_path}))
#         return docs
# 
#     def from_text(self, file_path: str) -> List[Document]:
#         # Placeholder implementation
#         with open(file_path, 'r') as f:
#             content = f.read()
#         return [Document(str(uuid.uuid4()), 'text', content, {'filepath': file_path})]
# 
#     def from_pdf(self, file_path: str) -> List[Document]:
#         """Extracts text from a PDF file."""
#         try:
#             with open(file_path, 'rb') as f:
#                 reader = pypdf.PdfReader(f)
#                 content = ""
#                 for page_num in range(len(reader.pages)):
#                     content += reader.pages[page_num].extract_text() + "\n"
#             # Create a single document for the entire PDF content
#             return [Document(str(uuid.uuid4()), 'pdf', content.strip(), {'filepath': file_path})]
#         except Exception as e:
#             print(f"Error reading PDF file {file_path}: {e}")
#             return []
# 
# class SemanticVectorStore:
#     def __init__(self):
#         self.documents: List[Document] = []
# 
#     def add_documents(self, documents: List[Document]):
#         self.documents.extend(documents)
# 
#     def semantic_search(self, query: str, top_k: int = 5, threshold: float = 0.0) -> List[Tuple[Document, str, float]]:
#         # Placeholder implementation - returns dummy results for testing structure
#         results = []
#         query_words = query.lower().split() # Split query into words
#         for doc in self.documents:
#             doc_content_lower = doc.content.lower()
#             # Check if any word from the query is in the document content
#             if any(word in doc_content_lower for word in query_words):
#                 results.append((doc, doc.content, 0.8)) # Dummy score
#             if len(results) >= top_k: break
#         return results
# 
#     def hybrid_search(self, query: str, top_k: int = 5) -> List[Tuple[Document, str, float]]:
#         # Placeholder implementation - combines semantic and keyword
#         semantic_res = self.semantic_search(query, top_k)
#         keyword_res = [(doc, doc.content, 0.5) for doc in self.documents if query.split(' ')[0].lower() in doc.content.lower()][:top_k]
#         return list(set(semantic_res + keyword_res))
# 
# class Answer:
#     def __init__(self, answer_text: str, citations: List[Dict[str, Any]], confidence_score: float):
#         self.answer_text = answer_text
#         self.citations = citations
#         self.confidence_score = confidence_score
# 
# class AnswerGenerator:
#     def __init__(self):
#         pass
# 
#     def generate_answer(self, query: str, chunks: List[Tuple[Document, str, float, str]], user: EnterpriseUser) -> Answer:
#         # Placeholder implementation
#         citation_list = []
#         combined_content = []
#         total_score = 0
# 
#         for doc, content_chunk, score, _type in chunks:
#             citation_list.append({
#                 'doc_id': doc.doc_id,
#                 'source': doc.metadata.get('source', 'unknown'),
#                 'page': doc.metadata.get('page', 'N/A'),
#                 'content_chunk': content_chunk
#             })
#             combined_content.append(content_chunk)
#             total_score += score
# 
#         avg_confidence = total_score / len(chunks) if chunks else 0.0
# 
#         # Simple answer generation for testing structure
#         answer_text = f"Based on the provided information, the query '{query}' relates to: {' '.join(combined_content)}. User {user.name} was querying."
# 
#         return Answer(answer_text, citation_list, avg_confidence)
# 
# class EnterpriseRAGSystem:
#     def __init__(self):
#         self.rbac_manager = RBACManager()
#         self.data_connector = DataSourceConnector()
#         self.vector_store = SemanticVectorStore()
#         self.answer_generator = AnswerGenerator()
# 
#     def ingest_data(self, file_path: str, data_type: str, classification: DataClassification, allowed_roles: List[UserRole], allowed_departments: List[str]) -> str:
#         # Placeholder implementation
#         docs = []
#         if data_type == 'text':
#             docs = self.data_connector.from_text(file_path)
#         elif data_type == 'csv':
#             docs = self.data_connector.from_csv(file_path)
#         elif data_type == 'json':
#             docs = self.data_connector.from_json(file_path)
#         elif data_type == 'pdf': # New condition for PDF
#             docs = self.data_connector.from_pdf(file_path)
# 
#         if docs:
#             for doc in docs:
#                 self.vector_store.add_documents([doc])
#                 policy = AccessPolicy(
#                     data_id=doc.doc_id,
#                     classification=classification,
#                     allowed_roles=allowed_roles,
#                     allowed_departments=allowed_departments
#                 )
#                 self.rbac_manager.register_policy(policy)
#             return docs[0].doc_id # Return the ID of the first document for testing
#         return None
# 
#     def query(self, query: str, user: EnterpriseUser) -> Tuple[Answer, str]:
#         # Placeholder implementation
#         # Perform search
#         search_results = self.vector_store.semantic_search(query, top_k=5)
# 
#         # Filter based on RBAC
#         authorized_chunks = []
#         security_status = "RBAC Check: "
#         for doc, chunk_content, score in search_results:
#             authorized, reason = self.rbac_manager.authorize_access(user, doc.doc_id)
#             security_status += f"({doc.doc_id}: {reason}) "
#             if authorized:
#                 authorized_chunks.append((doc, chunk_content, score, "semantic"))
# 
#         if not authorized_chunks:
#             return Answer("Access denied or no relevant information found.", [], 0.0), security_status
# 
#         # Generate answer
#         answer = self.answer_generator.generate_answer(query, authorized_chunks, user)
#         return answer, security_status

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install reportlab

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install reportlab

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install reportlab

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install reportlab

"""### Testing PDF Ingestion Feature

This test case will create a dummy PDF file, ingest it into the `EnterpriseRAGSystem`, and then query the system to ensure the content from the PDF can be successfully retrieved and processed.
"""

import tempfile
import os
import importlib

# Import necessary classes from the module
import enterprise_rag_system # Import the module
importlib.reload(enterprise_rag_system) # Reload to pick up changes

from enterprise_rag_system import (
    EnterpriseRAGSystem, EnterpriseUser, UserRole,
    DataClassification, Answer
)

print("Initializing Enterprise RAG System for PDF test...")
rag_system_pdf = EnterpriseRAGSystem()

# 1. Create a dummy PDF file
print("Creating a dummy PDF file...")
pdf_content = "This is a confidential project proposal. It outlines new strategies for Q1 2025 and is restricted to managers and executives."

# Using pypdf to create a simple PDF
from pypdf import PdfWriter
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

def create_dummy_pdf(file_path, text_content):
    c = canvas.Canvas(file_path, pagesize=letter)
    textobject = c.beginText()
    textobject.setTextOrigin(10, 750)
    for line in text_content.split('\n'):
        textobject.textLine(line)
    c.drawText(textobject)
    c.save()

with tempfile.NamedTemporaryFile(mode='wb', suffix='.pdf', delete=False) as f:
    pdf_path = f.name
    create_dummy_pdf(pdf_path, pdf_content)

print(f"Dummy PDF created at: {pdf_path}")

# 2. Ingest the PDF document with specific RBAC policies
print(f"Ingesting PDF document '{pdf_path}' with Manager/Executive access...")
pdf_doc_id = rag_system_pdf.ingest_data(
    file_path=pdf_path,
    data_type='pdf',
    classification=DataClassification.RESTRICTED,
    allowed_roles=[UserRole.EXECUTIVE, UserRole.MANAGER],
    allowed_departments=["Strategy", "Management"]
)

print(f"PDF Document ingested with ID: {pdf_doc_id}")

# 3. Create users with different roles for PDF test
manager_user = EnterpriseUser(
    user_id="man_susan",
    name="Susan Lee",
    department="Strategy",
    role=UserRole.MANAGER
)

analyst_user = EnterpriseUser(
    user_id="analyst_mike",
    name="Mike Green",
    department="Marketing",
    role=UserRole.ANALYST
)

print("\n--- Querying as Manager User (PDF Test) ---")
pdf_query = "What are the new strategies for Q1 2025?"
manager_answer, manager_security_status = rag_system_pdf.query(pdf_query, manager_user)

print(f"Manager User ({manager_user.name}) Query: '{pdf_query}'")
print(f"Answer: {manager_answer.answer_text}")
print(f"Confidence: {manager_answer.confidence_score:.2f}")
print(f"Security Status: {manager_security_status}")
print("Citations:")
for citation in manager_answer.citations:
    print(f"  - Doc ID: {citation['doc_id']}, Source: {citation['source']}, Chunk: {citation['content_chunk'][:50]}...")

print("\n--- Querying as Analyst User (PDF Test) ---")
analyst_answer, analyst_security_status = rag_system_pdf.query(pdf_query, analyst_user)

print(f"Analyst User ({analyst_user.name}) Query: '{pdf_query}'")
print(f"Answer: {analyst_answer.answer_text}")
print(f"Confidence: {analyst_answer.confidence_score:.2f}")
print(f"Security Status: {analyst_security_status}")

# Clean up the temporary PDF file
os.remove(pdf_path)
print(f"\nCleaned up temporary PDF file: {pdf_path}")